### ISSUE TITLE
Error with hardware accelerated OCR

### ISSUE THREAD

**Issue by yuginhc** [Xilinx/LSTM-PYNQ#1]
Hi, I installed BNN-PYNQ and LSTM-PYNQ on PYNQ v2.3 ( Arty Z7 board) 
the BNN-PYNQ works well but the LSTM-PYNQ doesn't work. 
When i run Hardware accelerated OCR, the error always occurs as following example. 
Can you help with this? 

Case 1
Weights: 4 bits Activations: 8 bits Parallelism: 1x

OSError                                   Traceback (most recent call last)
<ipython-input-24-1b4a3e51ac37> in <module>()
----> 1 W4A8_hw_ocr = lstm.PynqPlainOCR(network="W4A8", runtime=lstm.RUNTIME_HW)
      2 W4A8_hw_result = W4A8_hw_ocr.inference(im)
      3 W4A8_hw_mops_per_s, W4A8_hw_ms_inference_time, W4A8_hw_recognized_text = W4A8_hw_result
      4 W4A8_hw_ocr.cleanup()
      5 

/usr/local/lib/python3.6/dist-packages/lstm/ocr.py in __init__(self, runtime, network, load_overlay)
     92                                            network,
     93                                            load_overlay,
---> 94                                            PlainImagePreprocessor(self.input_size, int(network[-1])))
     95 
     96     @property

/usr/local/lib/python3.6/dist-packages/lstm/ocr.py in __init__(self, runtime, dataset, network, load_overlay, preprocessor)
     42 
     43     def __init__(self, runtime, dataset, network, load_overlay, preprocessor):
---> 44         super(PynqOCR, self).__init__(runtime, dataset, network, load_overlay)
     45         self.alphabet_path = os.path.join(LSTM_DATA_DIR, dataset, "alphabet.txt")
     46         self.preprocessor = preprocessor

/usr/local/lib/python3.6/dist-packages/lstm/lstm.py in __init__(self, runtime, dataset, network, load_overlay)
     62         if dllname not in self._libraries:
     63             self._libraries[dllname] = self._ffi.dlopen(
---> 64 		os.path.join(LSTM_LIB_DIR, dataset, network, dllname))
     65         self.interface = self._libraries[dllname]
     66         self._ffi.cdef(self.ffi_interface)

/usr/lib/python3/dist-packages/cffi/api.py in dlopen(self, name, flags)
    139         assert isinstance(name, basestring) or name is None
    140         with self._lock:
--> 141             lib, function_cache = _make_ffi_library(self, name, flags)
    142             self._function_caches.append(function_cache)
    143             self._libraries.append(lib)

/usr/lib/python3/dist-packages/cffi/api.py in _make_ffi_library(ffi, libname, flags)
    800 def _make_ffi_library(ffi, libname, flags):
    801     backend = ffi._backend
--> 802     backendlib = _load_backend_lib(backend, libname, flags)
    803     #
    804     def accessor_function(name):

/usr/lib/python3/dist-packages/cffi/api.py in _load_backend_lib(backend, name, flags)
    795         if first_error is not None:
    796             msg = "%s.  Additionally, %s" % (first_error, msg)
--> 797         raise OSError(msg)
    798     return backend.load_library(path, flags)
    799 

OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/lstm/libraries/plain/W4A8/libhw-plain-W4A8-ocr-pynq.so': libsds_lib.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/local/lib/python3.6/dist-packages/lstm/libraries/plain/W4A8/libhw-plain-W4A8-ocr-pynq.so'

I checked the LSTM library and found that the LSTM library has been successfully installed and the libhw-plain-W4A8-ocr-pynq.so is correctly located at /usr/local/lib/python3.6/dist-packages/lstm/libraries/plain/W4A8/libhw-plain-W4A8-ocr-pynq.so.

**Comment by volcacius** [comment]
Hi,
Unfortunately PYNQ 2.3 introduces some breaking changes, and I need to update the build and setup process around that. In the meantime, you should be able to work around the issue by installing the package and then:

- Create a soft symlink from libcma.so in the /usr/lib to libsds_lib.so:
`
sudo ln -s /usr/lib/libcma.so /usr/lib/libsds_lib.so
`

- Move the jupyter notebooks from where they end up into where they are supposed to be:
`
sudo mv /usr/local/lib/python3.6/dist-packages/home/xilinx/jupyter_notebooks/lstm /home/xilinx/jupyter_notebooks/
`

Let me know if this solves it for you.

**Comment by yuginhc** [comment]
Thank you so much for your help 

Create a soft symlink from libcma.so in the /usr/lib to libsds_lib.so:
sudo ln -s /usr/lib/libcma.so /usr/lib/libsds_lib.so

It solved the error

**Comment by meteorvanilla** [comment]
> Hi,
> Unfortunately PYNQ 2.3 introduces some breaking changes, and I need to update the build and setup process around that. In the meantime, you should be able to work around the issue by installing the package and then:
> 
> * Create a soft symlink from libcma.so in the /usr/lib to libsds_lib.so:
>   `sudo ln -s /usr/lib/libcma.so /usr/lib/libsds_lib.so`
> * Move the jupyter notebooks from where they end up into where they are supposed to be:
>   `sudo mv /usr/local/lib/python3.6/dist-packages/home/xilinx/jupyter_notebooks/lstm /home/xilinx/jupyter_notebooks/`
> 
> Let me know if this solves it for you.

Thank you so much, it also worked for me!

**Comment by 1430533056** [comment]
Thanks so much, it also works for me.

**Comment by giwon99** [comment]
thanks it also works for me
