### ISSUE TITLE
A problem about the *.so

### ISSUE THREAD

**Issue by dongzwhitsz** [Xilinx/LSTM-PYNQ#3]
I run the code as following:

    import lstm
    hw_ocr = lstm.PynqFrakturOCR(lstm.RUNTIME_HW)

But i get the following problem:
OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/lstm/libraries/fraktur/W5A5/libhw-fraktur-W5A5-ocr-pynq.so': libsds_lib.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/local/lib/python3.6/dist-packages/lstm/libraries/fraktur/W5A5/libhw-fraktur-W5A5-ocr-pynq.so'

I tried a lot, but I failed. Could I get some suggestion?

**Comment by giuliogamba** [comment]
Which version of PYNQ are you using? The current LSTM-PYNQ release supports PYNQ 2.0, but it seems you're using PYNQ 2.3. We will update the repo to support PYNQ 2.3 shortly. 
In the meanwhile, please check the workaround provided in #1: 
* Create a soft symlink from libcma.so in the /usr/lib to libsds_lib.so:
   `sudo ln -s /usr/lib/libcma.so /usr/lib/libsds_lib.so`
* Move the jupyter notebooks from where they end up into where they are supposed to be:
  `sudo mv /usr/local/lib/python3.6/dist-packages/home/xilinx/jupyter_notebooks/lstm /home/xilinx/jupyter_notebooks/`

**Comment by dongzwhitsz** [comment]
> Which version of PYNQ are you using? The current LSTM-PYNQ release supports PYNQ 2.0, but it seems you're using PYNQ 2.3. We will update the repo to support PYNQ 2.3 shortly.
> In the meanwhile, please check the workaround provided in #1:
> 
> * Create a soft symlink from libcma.so in the /usr/lib to libsds_lib.so:
>   `sudo ln -s /usr/lib/libcma.so /usr/lib/libsds_lib.so`
> * Move the jupyter notebooks from where they end up into where they are supposed to be:
>   `sudo mv /usr/local/lib/python3.6/dist-packages/home/xilinx/jupyter_notebooks/lstm /home/xilinx/jupyter_notebooks/`

Thank you very much. The reply helps me to solve the problem I met.Sorry for the unfamiliarity to github. I am a new.  I didn't noticed the solved error. Thankyou.
