### ISSUE TITLE
cma_alloc error while loading libhw*.so

### ISSUE THREAD

**Issue by ussamazahid96** [Xilinx/LSTM-PYNQ#4]
Hi,

I cross compiled `libhw-plain-W2A2-ocr-pynq.so` and `libsw-plain-W2A2-ocr-pynq.so` files as described in `src/README.md`. libsw works fine but while initiating hw_ocr with RUNTIME_HW I am getting the following error:

`OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/lstm_pynq-0.2-py3.6.egg/lstm/libraries/plain/W2A2/libhw-plain-W2A2-ocr-pynq.so': /usr/local/lib/python3.6/dist-packages/lstm_pynq-0.2-py3.6.egg/lstm/libraries/plain/W2A2/libhw-plain-W2A2-ocr-pynq.so: undefined symbol: cma_alloc.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/local/lib/python3.6/dist-packages/lstm_pynq-0.2-py3.6.egg/lstm/libraries/plain/W2A2/libhw-plain-W2A2-ocr-pynq.so'`

**Comment by giuliogamba** [comment]
Hi, this is a bug due to different libraries in different PYNQ images. Please refer to this: #1
